"use client";
import './globals.css';
import Header from '../../components/Header';
import { Inter } from 'next/font/google'
import Image from 'next/image';
import { useState } from 'react';
import { AiOutlineMenu, AiOutlineClose } from "react-icons/ai";
import Link from 'next/link';
import Contact from './contact/page';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

let Pages = [
  { name: "Home", link: "/" },
  { name: "Menu", link: "/menu" },
  { name: "Reviews", link: "/reviews" },
  { name: "About", link: "/aboutus" },
];


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [open, setOpen] = useState(false);

  return (
    <html lang="en" className='selection:text-white selection:bg-pink-700'>
      <body className={inter.className}>
      {/* <Header/> */}

{/* Header Components */}
<div  className=" w-full shadow-md fixed z-10  top-0 left-0 font-Poppins ">
        <div className="flex flex-col justify-center items-center  bg-gradient-to-b from-emerald-700 to-emerald-500  py-5 space-y-3">
        <Image className='py-2' src="/logo.png" width={129} height={129} alt="logo" />

          <div
            onClick={() => setOpen(!open)}
            className="text-2xl cursor-pointer lg:hidden p-3 rounded-full bg-white text-pink-600 "
          >
            {open ? <span className=" "><AiOutlineClose /></span>  : <span className=""><AiOutlineMenu /></span> }
          </div>
          <ul
            className={`lg:flex lg:justify-center lg:items-center   pt-2 md:pt-0  lg:pt-0 absolute lg:static text-gray-700 lg:text-white  bg-gray-200 lg:bg-transparent    lg:z-auto z-[-1] left-0  md:w-full lg:left-0 w-full  lg:pl-0 pl-0 transition-all duration-500 ease-in ${
              open
                ? "top-56 md:top-[225px] opacity-100"
                : "top-[-500px] opacity-0 md:opacity-100"
            } `}
          >
            {Pages.map((page, i) => {
              return (
                <li
                  key={i}
                  className=" text-xl md:my-0 my-2 p-2  text-center  cursor-pointer hover:bg-gray-300   lg:hover:bg-transparent  "
                >
                  <Link href={page.link}>{page.name}</Link>
                </li>
              );
            })}
          </ul>
        </div>
      </div>
{/* Header Components */}


        {children}


        {/* Footer Component */}
        <Contact />
        {/* Footer Component */}




        </body>
    </html>
  )
}
