"use client";
import './globals.css';
import Header from '../../components/Header';
import { Inter } from 'next/font/google'
import Image from 'next/image';
import { useState } from 'react';
import { AiOutlineMenu, AiOutlineClose, AiOutlineStar, AiOutlineUser } from "react-icons/ai";
import Link from 'next/link';
import Contact from './contact/page';
import ModernNav from '../../components/ModernNav';
import { AiOutlineHome } from 'react-icons/ai';
import { BsCurrencyRupee, BsInfo, BsInfoSquare } from 'react-icons/bs';
import { MdOutlineReviews } from 'react-icons/md';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

let Pages = [
  { name: "Home", link: "/" },
  { name: "Menu", link: "/menu" },
  { name: "Reviews", link: "/reviews" },
  { name: "About", link: "/aboutus" },
];


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [open, setOpen] = useState(false);

  return (
    <html lang="en" className='selection:text-white selection:bg-pink-700'>
      <body className={inter.className}>
      {/* <Header/> */}




{/* New Header */}
<Header/>
{/* New Header */}


        {children}


        {/* Footer Component */}
        <Contact />
        {/* Footer Component */}

{/* <ModernNav/> */}

<div className="ModernNav w-full fixed bottom-3 lg:bottom-4">
  <div className="container mx-auto">
        <div className="flex flex-row items-center justify-center space-x-3 bg-pink-400 py-2 mx-20 lg:mx-[520px] bg-opacity-50 backdrop-filter backdrop-blur-2xl rounded-xl">
          <span className=" bg-pink-700 p-2 rounded-xl"><Link href="/"><span className='text-2xl text-white'><AiOutlineHome/></span></Link></span>
          <span className=" bg-pink-700 p-2 rounded-xl"><Link href="/menu"><span className='text-2xl text-white'><BsCurrencyRupee/></span></Link></span>
          <span className=" bg-pink-700 p-2 rounded-xl"><Link href="/reviews"><span className='text-2xl text-white'><AiOutlineStar/></span></Link></span>
          <span className=" bg-pink-700 p-2 rounded-xl"><Link href="/aboutus"><span className='text-2xl text-white'><AiOutlineUser/></span></Link></span>
        </div>
  </div>
</div>


        </body>
    </html>
  )
}
